<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SteamKit2" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sts2Sync.Core.Tests" />
  </ItemGroup>

</Project>
